site_name: fanzijun-notes
docs_dir: notes
theme:
  name: gitbook
lang: zh
plugins:
  - search
extra_javascript:
  - javascripts/extra.js
  # KaTeX åº“
  - https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@latest/dist/contrib/auto-render.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css
  - https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
  - stylesheets/extra.css